version: '3'

services:
  app_preprod:
    build:
      context: .
      args:
        - ENV=preprod
    container_name: backend_preprod
    depends_on:
      - dbmysql_preprod
    links:
      - dbmysql_preprod
    volumes:
      -  ./:/home/app/
    expose:
      - 80
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql_preprod:3306/database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=api-opendata.preprod.nonstopintegration.ml
      - LETSENCRYPT_HOST=api-opendata.preprod.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

  dbmysql_preprod:
    user: "1000:50"
    image: mysql:5.7.32
    container_name: dbmysql_preprod
    volumes:
      - mysql_preprod:/var/lib/localsql
      - mysql_data_preprod:/var/lib/localsql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  mysql_data_preprod:
  mysql_preprod:

networks:
  default:
    external:
      name: webproxy