version: '3'

services:
  backend_opendata_dev:
    build:
      context: .
      args:
        - ENV=dev
    network_mode: bridge
    container_name: backend_opendata_dev
    depends_on:
      - dbmysql_dev
    links:
      - dbmysql_dev
    volumes:
      -  ./:/home/app/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql_dev:3306/database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 7001:8080

  dbmysql_dev:
    user: "1000:50"
    image: mysql:5.7.32
    network_mode: bridge
    container_name: dbmysql_dev
    volumes:
      - mysql_dev:/var/lib/localsql
      - mysql_data_dev:/var/lib/localsql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  mysql_data_dev:
  mysql_dev: