version: '3'

services:
  app_prod:
    build:
      context: .
      args:
        - ENV=prod
    image: backend_prod
    container_name: backend_prod
    depends_on:
      - dbmysql_prod
    links:
      - dbmysql_prod
    volumes:
      -  ./:/home/app/
    expose:
      - 80
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql_prod:3306/database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=api-opendata.nonstopintegration.ml
      - LETSENCRYPT_HOST=api-opendata.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

  dbmysql_prod:
    user: "1000:50"
    image: mysql:5.7.32
    container_name: dbmysql_prod
    volumes:
      - mysql_dev:/var/lib/localsql
      - mysql_data_dev:/var/lib/localsql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  mysql_data_prod:
  mysql_prod:

networks:
  default:
    external:
      name: webproxy